/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_62 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] booleanFinal
  );
  
  
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'he: begin
        booleanFinal = a | b;
      end
      default: begin
        booleanFinal = a & b;
      end
    endcase
  end
endmodule
