/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_38 (
    input [5:0] alufn,
    input z,
    output reg [7:0] cmpFinal
  );
  
  
  
  reg cmpVal;
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        cmpVal = z;
      end
      default: begin
        cmpVal = 1'h0;
      end
    endcase
    cmpFinal[0+0-:1] = cmpVal;
    cmpFinal[1+6-:7] = 7'h00;
  end
endmodule
