/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 4
     DIV = 25
     TOP = 9
     UP = 1
*/
module counter_3 (
    input clk,
    input rst,
    output reg [3:0] value
  );
  
  localparam SIZE = 3'h4;
  localparam DIV = 5'h19;
  localparam TOP = 4'h9;
  localparam UP = 1'h1;
  
  
  reg [28:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 29'h13ffffff;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[25+3-:4];
    if (1'h1) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 29'h13ffffff) begin
        M_ctr_d = 1'h0;
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 29'h13ffffff;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
