/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module operatorseg_18 (
    input [3:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'h0f;
      end
      1'h1: begin
        segs = 8'h03;
      end
      2'h2: begin
        segs = 8'hf0;
      end
      default: begin
        segs = 8'h00;
      end
    endcase
  end
endmodule
