/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_51 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] shifterResult
  );
  
  
  
  always @* begin
    
    case (alufn[0+2-:3])
      3'h0: begin
        shifterResult = a << b;
      end
      3'h1: begin
        shifterResult = a >> b;
      end
      default: begin
        shifterResult[0+7-:8] = a << b;
      end
    endcase
  end
endmodule
